[package]
name = "compiler"
description = "Compiler for the Jack language into stack VM code"
version = "0.1.0"
authors = ["Eugene Obrezkov <ghaiklor@gmail.com>"]
edition = "2018"
workspace = "../.."

[dependencies]
clap = "2.33.0"
